package net.eca.util.health;

public enum HealthSolveFailure {
    NONE,
    LOCATION_NOT_FOUND,
    CALL_NOT_RESOLVED,
    INVERTER_MISSING,
    MULTI_LOCATION_UNSUPPORTED,
    VALUE_NOT_REPRESENTABLE,
    WRITE_FAILED,
    VERIFY_FAILED,
    ROLLBACK_FAILED
}
